[project]
name = "thai-wordcards"
version = "0.3.0b3"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "TangziWuyue", email = "1019853751@qq.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
thai-wordcards = "thai_wordcards:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
